# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radio_protocol_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='radio_protocol_command.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1cradio_protocol_command.proto\"\xa1\x01\n\x14RadioProtocolCommand\x12\x10\n\x08robot_id\x18\x01 \x02(\x05\x12\x12\n\nvelocity_x\x18\x02 \x02(\x02\x12\x12\n\nvelocity_y\x18\x03 \x02(\x02\x12\x12\n\nvelocity_r\x18\x04 \x02(\x02\x12\x11\n\tflat_kick\x18\x05 \x01(\x02\x12\x11\n\tchip_kick\x18\x06 \x01(\x02\x12\x15\n\rdribbler_spin\x18\x07 \x01(\x02')
)




_RADIOPROTOCOLCOMMAND = _descriptor.Descriptor(
  name='RadioProtocolCommand',
  full_name='RadioProtocolCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='RadioProtocolCommand.robot_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_x', full_name='RadioProtocolCommand.velocity_x', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_y', full_name='RadioProtocolCommand.velocity_y', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity_r', full_name='RadioProtocolCommand.velocity_r', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flat_kick', full_name='RadioProtocolCommand.flat_kick', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chip_kick', full_name='RadioProtocolCommand.chip_kick', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dribbler_spin', full_name='RadioProtocolCommand.dribbler_spin', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=194,
)

DESCRIPTOR.message_types_by_name['RadioProtocolCommand'] = _RADIOPROTOCOLCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadioProtocolCommand = _reflection.GeneratedProtocolMessageType('RadioProtocolCommand', (_message.Message,), dict(
  DESCRIPTOR = _RADIOPROTOCOLCOMMAND,
  __module__ = 'radio_protocol_command_pb2'
  # @@protoc_insertion_point(class_scope:RadioProtocolCommand)
  ))
_sym_db.RegisterMessage(RadioProtocolCommand)


# @@protoc_insertion_point(module_scope)
