# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radio_protocol_wrapper.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import radio_protocol_command_pb2 as radio__protocol__command__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='radio_protocol_wrapper.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1cradio_protocol_wrapper.proto\x1a\x1cradio_protocol_command.proto\">\n\x14RadioProtocolWrapper\x12&\n\x07\x63ommand\x18\x01 \x03(\x0b\x32\x15.RadioProtocolCommand')
  ,
  dependencies=[radio__protocol__command__pb2.DESCRIPTOR,])




_RADIOPROTOCOLWRAPPER = _descriptor.Descriptor(
  name='RadioProtocolWrapper',
  full_name='RadioProtocolWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='RadioProtocolWrapper.command', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=124,
)

_RADIOPROTOCOLWRAPPER.fields_by_name['command'].message_type = radio__protocol__command__pb2._RADIOPROTOCOLCOMMAND
DESCRIPTOR.message_types_by_name['RadioProtocolWrapper'] = _RADIOPROTOCOLWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadioProtocolWrapper = _reflection.GeneratedProtocolMessageType('RadioProtocolWrapper', (_message.Message,), dict(
  DESCRIPTOR = _RADIOPROTOCOLWRAPPER,
  __module__ = 'radio_protocol_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:RadioProtocolWrapper)
  ))
_sym_db.RegisterMessage(RadioProtocolWrapper)


# @@protoc_insertion_point(module_scope)
