# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0brobot.proto\"\x8b\x02\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1b\n\x04move\x18\x02 \x01(\x0b\x32\r.Command.Move\x12\x1f\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32\x0f.Command.Action\x12\"\n\x08settings\x18\x04 \x03(\x0b\x32\x10.Command.Setting\x1a\'\n\x04Move\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01r\x18\x03 \x01(\x02\x1a\x35\n\x06\x41\x63tion\x12\x0f\n\x07\x64ribble\x18\x01 \x01(\x02\x12\x0c\n\x04kick\x18\x02 \x01(\x02\x12\x0c\n\x04\x63hip\x18\x03 \x01(\x02\x1a\x32\n\x07Setting\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\x89\x01\n\x0cMeasurements\x12\n\n\x02id\x18\x01 \x01(\r\x12*\n\x0cmeasurements\x18\x02 \x03(\x0b\x32\x14.Measurements.Single\x1a\x41\n\x06Single\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x19\n\x11tenFoldMultiplier\x18\x03 \x01(\x05\x42$\n\"org.ssh.ipc.serialization.protobufb\x06proto3')
)




_COMMAND_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='Command.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Command.Move.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='Command.Move.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='Command.Move.r', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=176,
)

_COMMAND_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='Command.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dribble', full_name='Command.Action.dribble', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kick', full_name='Command.Action.kick', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chip', full_name='Command.Action.chip', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=231,
)

_COMMAND_SETTING = _descriptor.Descriptor(
  name='Setting',
  full_name='Command.Setting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Command.Setting.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Command.Setting.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Command.Setting.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=283,
)

_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Command.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='move', full_name='Command.move', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='Command.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settings', full_name='Command.settings', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_COMMAND_MOVE, _COMMAND_ACTION, _COMMAND_SETTING, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=283,
)


_MEASUREMENTS_SINGLE = _descriptor.Descriptor(
  name='Single',
  full_name='Measurements.Single',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='Measurements.Single.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Measurements.Single.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tenFoldMultiplier', full_name='Measurements.Single.tenFoldMultiplier', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=423,
)

_MEASUREMENTS = _descriptor.Descriptor(
  name='Measurements',
  full_name='Measurements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Measurements.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='measurements', full_name='Measurements.measurements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MEASUREMENTS_SINGLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=423,
)

_COMMAND_MOVE.containing_type = _COMMAND
_COMMAND_ACTION.containing_type = _COMMAND
_COMMAND_SETTING.containing_type = _COMMAND
_COMMAND.fields_by_name['move'].message_type = _COMMAND_MOVE
_COMMAND.fields_by_name['action'].message_type = _COMMAND_ACTION
_COMMAND.fields_by_name['settings'].message_type = _COMMAND_SETTING
_MEASUREMENTS_SINGLE.containing_type = _MEASUREMENTS
_MEASUREMENTS.fields_by_name['measurements'].message_type = _MEASUREMENTS_SINGLE
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['Measurements'] = _MEASUREMENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(

  Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), dict(
    DESCRIPTOR = _COMMAND_MOVE,
    __module__ = 'robot_pb2'
    # @@protoc_insertion_point(class_scope:Command.Move)
    ))
  ,

  Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
    DESCRIPTOR = _COMMAND_ACTION,
    __module__ = 'robot_pb2'
    # @@protoc_insertion_point(class_scope:Command.Action)
    ))
  ,

  Setting = _reflection.GeneratedProtocolMessageType('Setting', (_message.Message,), dict(
    DESCRIPTOR = _COMMAND_SETTING,
    __module__ = 'robot_pb2'
    # @@protoc_insertion_point(class_scope:Command.Setting)
    ))
  ,
  DESCRIPTOR = _COMMAND,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  ))
_sym_db.RegisterMessage(Command)
_sym_db.RegisterMessage(Command.Move)
_sym_db.RegisterMessage(Command.Action)
_sym_db.RegisterMessage(Command.Setting)

Measurements = _reflection.GeneratedProtocolMessageType('Measurements', (_message.Message,), dict(

  Single = _reflection.GeneratedProtocolMessageType('Single', (_message.Message,), dict(
    DESCRIPTOR = _MEASUREMENTS_SINGLE,
    __module__ = 'robot_pb2'
    # @@protoc_insertion_point(class_scope:Measurements.Single)
    ))
  ,
  DESCRIPTOR = _MEASUREMENTS,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:Measurements)
  ))
_sym_db.RegisterMessage(Measurements)
_sym_db.RegisterMessage(Measurements.Single)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\"org.ssh.ipc.serialization.protobuf'))
# @@protoc_insertion_point(module_scope)
